# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20170125_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
